#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    #line 2 "..\..\Views\Manage\ManageLogins.cshtml"
    using Microsoft.Owin.Security;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Manage/ManageLogins.cshtml")]
    public partial class _Views_Manage_ManageLogins_cshtml : System.Web.Mvc.WebViewPage<IWSProject.Models.ManageLoginsViewModel>
    {
        public _Views_Manage_ManageLogins_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Manage\ManageLogins.cshtml"
  
    ViewBag.Title = "Manage your external logins";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"accountHeader\"");

WriteLiteral(">\r\n    <h2>");

            
            #line 8 "..\..\Views\Manage\ManageLogins.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n</div>\r\n<p>");

            
            #line 10 "..\..\Views\Manage\ManageLogins.cshtml"
Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 11 "..\..\Views\Manage\ManageLogins.cshtml"
  
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    if (loginProviders.Count() == 0) {

            
            #line default
            #line hidden
WriteLiteral("        <div>\r\n            <p>\r\n                There are no external authenticat" +
"ion services configured. See <a");

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=313242\"");

WriteLiteral(">this article</a>\r\n                for details on setting up this ASP.NET applica" +
"tion to support logging in via external services.\r\n            </p>\r\n        </d" +
"iv>\r\n");

            
            #line 20 "..\..\Views\Manage\ManageLogins.cshtml"
    }
    else
    {
        if (Model.CurrentLogins.Count > 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <h4>Registered Logins</h4>\r\n");

WriteLiteral("            <table>\r\n                <tbody>\r\n");

            
            #line 28 "..\..\Views\Manage\ManageLogins.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Manage\ManageLogins.cshtml"
                     foreach (var account in Model.CurrentLogins)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n                            <td>");

            
            #line 31 "..\..\Views\Manage\ManageLogins.cshtml"
                           Write(account.LoginProvider);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>\r\n");

            
            #line 33 "..\..\Views\Manage\ManageLogins.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Manage\ManageLogins.cshtml"
                                 if (ViewBag.ShowRemoveButton)
                                {
                                    using (Html.BeginForm("RemoveLogin", "Manage"))
                                    {
                                        
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Manage\ManageLogins.cshtml"
                                   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Manage\ManageLogins.cshtml"
                                                                
                                        
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Manage\ManageLogins.cshtml"
                                   Write(Html.Hidden("loginProvider", account.LoginProvider));

            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Manage\ManageLogins.cshtml"
                                                                                            
                                        
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Manage\ManageLogins.cshtml"
                                   Write(Html.Hidden("providerKey", account.ProviderKey));

            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Manage\ManageLogins.cshtml"
                                                                                        

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Remove\"");

WriteAttribute("title", Tuple.Create(" title=\"", 1641), Tuple.Create("\"", 1707)
, Tuple.Create(Tuple.Create("", 1649), Tuple.Create("Remove", 1649), true)
, Tuple.Create(Tuple.Create(" ", 1655), Tuple.Create("this", 1656), true)
            
            #line 40 "..\..\Views\Manage\ManageLogins.cshtml"
              , Tuple.Create(Tuple.Create(" ", 1660), Tuple.Create<System.Object, System.Int32>(account.LoginProvider
            
            #line default
            #line hidden
, 1661), false)
, Tuple.Create(Tuple.Create(" ", 1683), Tuple.Create("login", 1684), true)
, Tuple.Create(Tuple.Create(" ", 1689), Tuple.Create("from", 1690), true)
, Tuple.Create(Tuple.Create(" ", 1694), Tuple.Create("your", 1695), true)
, Tuple.Create(Tuple.Create(" ", 1699), Tuple.Create("account", 1700), true)
);

WriteLiteral(" />\r\n");

            
            #line 41 "..\..\Views\Manage\ManageLogins.cshtml"
                                    }
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    ");

WriteLiteral(" &nbsp;\r\n");

            
            #line 46 "..\..\Views\Manage\ManageLogins.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </td>\r\n                        </tr>\r\n");

            
            #line 49 "..\..\Views\Manage\ManageLogins.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tbody>\r\n            </table>\r\n");

            
            #line 52 "..\..\Views\Manage\ManageLogins.cshtml"
        }
        if (Model.OtherLogins.Count > 0)
        {
            using (Html.BeginForm("LinkLogin", "Manage"))
            {
                
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Manage\ManageLogins.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Manage\ManageLogins.cshtml"
                                        

            
            #line default
            #line hidden
WriteLiteral("                <p>\r\n");

            
            #line 59 "..\..\Views\Manage\ManageLogins.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\Manage\ManageLogins.cshtml"
                     foreach (AuthenticationDescription p in Model.OtherLogins)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <button");

WriteLiteral(" type=\"submit\"");

WriteAttribute("id", Tuple.Create(" id=\"", 2429), Tuple.Create("\"", 2455)
            
            #line 61 "..\..\Views\Manage\ManageLogins.cshtml"
, Tuple.Create(Tuple.Create("", 2434), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 2434), false)
);

WriteLiteral(" name=\"provider\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2472), Tuple.Create("\"", 2501)
            
            #line 61 "..\..\Views\Manage\ManageLogins.cshtml"
                , Tuple.Create(Tuple.Create("", 2480), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 2480), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 2502), Tuple.Create("\"", 2546)
, Tuple.Create(Tuple.Create("", 2510), Tuple.Create("Log", 2510), true)
, Tuple.Create(Tuple.Create(" ", 2513), Tuple.Create("in", 2514), true)
, Tuple.Create(Tuple.Create(" ", 2516), Tuple.Create("using", 2517), true)
, Tuple.Create(Tuple.Create(" ", 2522), Tuple.Create("your", 2523), true)
            
            #line 61 "..\..\Views\Manage\ManageLogins.cshtml"
                                                               , Tuple.Create(Tuple.Create(" ", 2527), Tuple.Create<System.Object, System.Int32>(p.Caption
            
            #line default
            #line hidden
, 2528), false)
, Tuple.Create(Tuple.Create(" ", 2538), Tuple.Create("account", 2539), true)
);

WriteLiteral(">");

            
            #line 61 "..\..\Views\Manage\ManageLogins.cshtml"
                                                                                                                                                               Write(p.AuthenticationType);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 62 "..\..\Views\Manage\ManageLogins.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </p>\r\n");

            
            #line 64 "..\..\Views\Manage\ManageLogins.cshtml"
            }
        }
    }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
