/*
Deployment script for consolid

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "consolid"
:setvar DefaultFilePrefix "consolid"
:setvar DefaultDataPath "C:\Users\dogho\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\mssqllocaldb\"
:setvar DefaultLogPath "C:\Users\dogho\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\mssqllocaldb\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping unnamed constraint on [dbo].[MasterCompta]...';


GO
ALTER TABLE [dbo].[MasterCompta] DROP CONSTRAINT [DF__MasterCom__Trans__704B2900];


GO
PRINT N'Dropping unnamed constraint on [dbo].[MasterCompta]...';


GO
ALTER TABLE [dbo].[MasterCompta] DROP CONSTRAINT [DF__MasterCom__ItemD__713F4D39];


GO
PRINT N'Dropping unnamed constraint on [dbo].[MasterCompta]...';


GO
ALTER TABLE [dbo].[MasterCompta] DROP CONSTRAINT [DF__MasterCom__Entry__72337172];


GO
PRINT N'Dropping [dbo].[FK_MasterCompta_Account]...';


GO
ALTER TABLE [dbo].[MasterCompta] DROP CONSTRAINT [FK_MasterCompta_Account];


GO
PRINT N'Dropping [dbo].[FK_MasterCompta_Company]...';


GO
ALTER TABLE [dbo].[MasterCompta] DROP CONSTRAINT [FK_MasterCompta_Company];


GO
PRINT N'Dropping [dbo].[FK_MasterCompta_CostCenter]...';


GO
ALTER TABLE [dbo].[MasterCompta] DROP CONSTRAINT [FK_MasterCompta_CostCenter];


GO
PRINT N'Dropping [dbo].[FK_MasterCompta_TypeJournal]...';


GO
ALTER TABLE [dbo].[MasterCompta] DROP CONSTRAINT [FK_MasterCompta_TypeJournal];


GO
PRINT N'Dropping [dbo].[FK_DetailCompta_MasterCompta]...';


GO
ALTER TABLE [dbo].[DetailCompta] DROP CONSTRAINT [FK_DetailCompta_MasterCompta];


GO
PRINT N'Starting rebuilding table [dbo].[MasterCompta]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_MasterCompta] (
    [id]          INT             IDENTITY (1, 1) NOT NULL,
    [oid]         INT             NOT NULL,
    [CostCenter]  NVARCHAR (50)   NOT NULL,
    [account]     NVARCHAR (50)   NOT NULL,
    [HeaderText]  NVARCHAR (250)  NULL,
    [TransDate]   DATE            DEFAULT (getdate()) NOT NULL,
    [ItemDate]    DATE            DEFAULT (getdate()) NOT NULL,
    [EntryDate]   DATE            DEFAULT (getdate()) NOT NULL,
    [CompanyId]   NVARCHAR (50)   NOT NULL,
    [FileName]    NVARCHAR (255)  NULL,
    [FileContent] VARBINARY (MAX) NULL,
    [IsValidated] BIT             NULL,
    [oTotal]      AS              ([dbo].[GetMasterComptaTotal]([id])),
    [oCurrency]   AS              ([dbo].[GetMasterComptaCurrency]([id])),
    [oPeriode]    AS              ([dbo].[GetMasterComptaPeriode]([id])),
    [oYear]       AS              ([dbo].[GetMasterComptaYear]([id])),
    [oMonth]      AS              ([dbo].[GetMasterComptaMonth]([id])),
    [TypeJournal] VARCHAR (50)    NULL,
    [ModelId]     INT             NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_MasterCompta$PrimaryKey1] PRIMARY KEY CLUSTERED ([id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[MasterCompta])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_MasterCompta] ON;
        INSERT INTO [dbo].[tmp_ms_xx_MasterCompta] ([id], [oid], [CostCenter], [account], [HeaderText], [TransDate], [ItemDate], [EntryDate], [CompanyId], [IsValidated], [TypeJournal], [ModelId])
        SELECT   [id],
                 [oid],
                 [CostCenter],
                 [account],
                 [HeaderText],
                 [TransDate],
                 [ItemDate],
                 [EntryDate],
                 [CompanyId],
                 [IsValidated],
                 [TypeJournal],
                 [ModelId]
        FROM     [dbo].[MasterCompta]
        ORDER BY [id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_MasterCompta] OFF;
    END

DROP TABLE [dbo].[MasterCompta];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_MasterCompta]', N'MasterCompta';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_MasterCompta$PrimaryKey1]', N'MasterCompta$PrimaryKey', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[FK_MasterCompta_Account]...';


GO
ALTER TABLE [dbo].[MasterCompta] WITH NOCHECK
    ADD CONSTRAINT [FK_MasterCompta_Account] FOREIGN KEY ([account]) REFERENCES [dbo].[Account] ([id]);


GO
PRINT N'Creating [dbo].[FK_MasterCompta_Company]...';


GO
ALTER TABLE [dbo].[MasterCompta] WITH NOCHECK
    ADD CONSTRAINT [FK_MasterCompta_Company] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Company] ([id]);


GO
PRINT N'Creating [dbo].[FK_MasterCompta_CostCenter]...';


GO
ALTER TABLE [dbo].[MasterCompta] WITH NOCHECK
    ADD CONSTRAINT [FK_MasterCompta_CostCenter] FOREIGN KEY ([CostCenter]) REFERENCES [dbo].[CostCenter] ([id]);


GO
PRINT N'Creating [dbo].[FK_MasterCompta_TypeJournal]...';


GO
ALTER TABLE [dbo].[MasterCompta] WITH NOCHECK
    ADD CONSTRAINT [FK_MasterCompta_TypeJournal] FOREIGN KEY ([TypeJournal]) REFERENCES [dbo].[TypeJournal] ([Id]);


GO
PRINT N'Creating [dbo].[FK_DetailCompta_MasterCompta]...';


GO
ALTER TABLE [dbo].[DetailCompta] WITH NOCHECK
    ADD CONSTRAINT [FK_DetailCompta_MasterCompta] FOREIGN KEY ([transid]) REFERENCES [dbo].[MasterCompta] ([id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[MasterCompta] WITH CHECK CHECK CONSTRAINT [FK_MasterCompta_Account];

ALTER TABLE [dbo].[MasterCompta] WITH CHECK CHECK CONSTRAINT [FK_MasterCompta_Company];

ALTER TABLE [dbo].[MasterCompta] WITH CHECK CHECK CONSTRAINT [FK_MasterCompta_CostCenter];

ALTER TABLE [dbo].[MasterCompta] WITH CHECK CHECK CONSTRAINT [FK_MasterCompta_TypeJournal];

ALTER TABLE [dbo].[DetailCompta] WITH CHECK CHECK CONSTRAINT [FK_DetailCompta_MasterCompta];


GO
PRINT N'Update complete.';


GO
