<?xml version="1.0" encoding="utf-8"?><Database Name="DB_A18F7E_iws_07" Class="IWSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\mssqllocaldb;Initial Catalog=DB_A18F7E_iws_07;Integrated Security=True;MultipleActiveResultSets=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PeriodicAccountBalance" Member="PeriodicAccountBalances">
    <Type Name="PeriodicAccountBalance">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="AccountId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Periode" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Debit" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Credit" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FinalBalance" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="InitialBalance" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="oYear" Type="System.String" DbType="Char(4)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="oMonth" Type="System.String" DbType="Char(2)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ModelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDebit" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ICredit" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="FDebit" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="FCredit" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="Account_PeriodicAccountBalance" Member="Account" ThisKey="AccountId" OtherKey="id" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FiscalYear" Member="FiscalYears">
    <Type Name="FiscalYear">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Period" Type="System.String" DbType="NChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Current]" Member="Current" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Open]" Member="Open" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ModelId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DepreciationDetail" Member="DepreciationDetails">
    <Type Name="DepreciationDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TransId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Period" Type="System.String" DbType="NVarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="Depreciation" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Accumulated" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="BookValue" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Percentage" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsValidated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.xxBalance" Member="xxBalances">
    <Type Name="xxBalance">
      <Column Name="ClassId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ClassName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SubClassId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SubClassName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AccountId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TDebit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TCredit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsDebit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="dateofopen" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="dateofclose" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="balance" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsDebit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBalanceSheetAccount" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Posted" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="TypeJournal" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ModelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsResultAccount" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsIncomeStatementAccount" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Account_PeriodicAccountBalance" Member="PeriodicAccountBalances" ThisKey="id" OtherKey="AccountId" Type="PeriodicAccountBalance" />
    </Type>
  </Table>
  <Function Name="dbo.account1To7" Method="account1To7">
    <Parameter Name="start" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="end" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="companyid" Type="System.String" DbType="NVarChar(6)" />
    <ElementType Name="account1To7Result">
      <Column Name="gr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="AccountId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TDebit" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TCredit" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="SDebit" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="SCredit" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ClassAccountBalance" Method="ClassAccountBalance">
    <Parameter Name="class" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="start" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="end" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="companyid" Type="System.String" DbType="NVarChar(6)" />
    <ElementType Name="ClassAccountBalanceResult">
      <Column Name="ID" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="AccountId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TDebit" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TCredit" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="SDebit" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="SCredit" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ClassAccountBalances" Method="ClassAccountBalances">
    <Parameter Name="start" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="end" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="companyid" Type="System.String" DbType="NVarChar(6)" />
    <ElementType Name="ClassAccountBalancesResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ClassName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SubClassId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SubClassName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AccountId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TDebit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TCredit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SDebit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SCredit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsBalance" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAccountBalance" Method="GetAccountBalance" IsComposable="true">
    <Parameter Name="id" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="start" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="end" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="companyid" Type="System.String" DbType="NVarChar(6)" />
    <ElementType Name="GetAccountBalanceResult">
      <Column Name="AccountId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Debit" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Credit" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAccountBalances" Method="GetAccountBalances" IsComposable="true">
    <Parameter Name="class" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="start" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="end" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="companyid" Type="System.String" DbType="NVarChar(6)" />
    <ElementType Name="GetAccountBalancesResult">
      <Column Name="AccountId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TDebit" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TCredit" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="SDebit" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="SCredit" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetBalanceSheetChildren" Method="GetBalanceSheetChildren" IsComposable="true">
    <Parameter Name="id" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="companyid" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="isBalanceSheetAccount" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="GetBalanceSheetChildrenResult">
      <Column Name="id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetChildren" Method="GetChildren" IsComposable="true">
    <Parameter Name="id" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="companyid" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetChildrenResult">
      <Column Name="id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetParents" Method="GetParents" IsComposable="true">
    <Parameter Name="id" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="companyid" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetParentsResult">
      <Column Name="id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LogException" Method="LogException">
    <Parameter Name="Message" Parameter="message" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Source" Parameter="source" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="URL" Parameter="uRL" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Target" Parameter="target" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="ComapnyId" Parameter="comapnyId" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(6)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetFiscalYears" Method="GetFiscalYears">
    <Parameter Name="companyid" Type="System.String" DbType="NVarChar(6)" />
    <ElementType Name="GetFiscalYearsResult">
      <Column Name="CompanyId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CStart" Type="System.String" DbType="NChar(6)" CanBeNull="true" />
      <Column Name="CEnd" Type="System.String" DbType="NChar(6)" CanBeNull="true" />
      <Column Name="OStart" Type="System.String" DbType="NChar(6)" CanBeNull="true" />
      <Column Name="OEnd" Type="System.String" DbType="NChar(6)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CloseFiscalYear" Method="CloseFiscalYear">
    <Parameter Name="companyId" Type="System.String" DbType="NVarChar(6)" />
    <ElementType Name="CloseFiscalYearResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="AccountId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Periode" Type="System.String" DbType="NChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Debit" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Credit" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="InitialBalance" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="FinalBalance" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="oYear" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="oMonth" Type="System.String" DbType="Char(2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.OpenFiscalYear" Method="OpenFiscalYear">
    <Parameter Name="NStart" Parameter="nStart" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="NEnd" Parameter="nEnd" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="CompanyId" Parameter="companyId" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Current" Parameter="current" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Open" Parameter="open" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetBrouillard" Method="GetBrouillard">
    <Parameter Name="TypeDoc" Parameter="typeDoc" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="NumPiece" Parameter="numPiece" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="CompanyId" Parameter="companyId" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="ItemId" Parameter="itemId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetBrouillardResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Period" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NumPiece" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="AccountID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Side" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OAccountID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owner" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HeaderText" Type="System.String" DbType="NVarChar(306) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TypeDoc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsValidated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SetTypeJournal" Method="SetTypeJournal">
    <Parameter Name="typedoc" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="transid" Type="System.Int32" DbType="Int" />
    <Parameter Name="companyid" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetChild" Method="GetChild" IsComposable="true">
    <Parameter Name="classId" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="companyid" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetChildResult">
      <Column Name="ChildId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChildName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ParentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ClassChildren" Method="ClassChildren">
    <Parameter Name="classId" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="company" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="ClassChildrenResult">
      <Column Name="id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ClassChild" Method="ClassChild">
    <Parameter Name="classId" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="company" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="ClassChildResult">
      <Column Name="ChildId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChildName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ParentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AccountBalance" Method="AccountBalance1">
    <Parameter Name="class" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="start" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="end" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="companyid" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="isBalance" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="AccountBalanceResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ClassName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SubClassId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SubClassName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AccountId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TDebit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TCredit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SDebit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SCredit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsBalance" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsResult" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SetJournal" Method="SetJournal">
    <Parameter Name="transid" Type="System.Int32" DbType="Int" />
    <Parameter Name="companyid" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PeriodicBalances" Method="PeriodicBalances">
    <Parameter Name="start" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="end" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="selectedIDs" Type="System.String" DbType="NVarChar(550)" />
    <Parameter Name="companyid" Type="System.String" DbType="NVarChar(4)" />
    <ElementType Name="PeriodicBalancesResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Periode" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="OYear" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="OMonth" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="Debit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Credit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="InitialBalance" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="FinalBalance" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SDebit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SCredit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsBalance" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetJournal" Method="GetJournal">
    <Parameter Name="start" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="end" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="uiculture" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="Companyid" Parameter="companyid" Type="System.String" DbType="NVarChar(6)" />
    <ElementType Name="GetJournalResult1">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LocalName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CustSupplierID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TransDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ItemDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Periode" Type="System.String" DbType="NChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="OYear" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="oMonth" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="Account" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="OAccount" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OAccountName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CreditAvantImputationAmount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="DebitAvantImputationAmount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Side" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owner" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TypeJournal" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Info" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ClassAccountBalance" Method="ClassAccountBalance1" IsComposable="true">
    <Parameter Name="class" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="start" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="end" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="companyid" Type="System.String" DbType="NVarChar(6)" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.IncomesAndBalance" Method="IncomesAndBalance">
    <Parameter Name="period" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="companyid" Type="System.String" DbType="NVarChar(6)" />
    <ElementType Name="IncomesAndBalanceResult">
      <Column Name="ClassId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ClassName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SubClassId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SubClassName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AccountId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TDebit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TCredit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsDebit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>