#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Manage/SetPassword.cshtml")]
    public partial class _Views_Manage_SetPassword_cshtml : System.Web.Mvc.WebViewPage<IWSProject.Models.SetPasswordViewModel>
    {
        public _Views_Manage_SetPassword_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 4 "..\..\Views\Manage\SetPassword.cshtml"
  
    ViewBag.Title = "Set password";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"accountHeader\"");

WriteLiteral(">\r\n    <h2>");

            
            #line 9 "..\..\Views\Manage\SetPassword.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n    <p>You do not have a local username/password for this site. Add a loca" +
"l account so you can log in without an external login.</p>\r\n</div>\r\n");

            
            #line 12 "..\..\Views\Manage\SetPassword.cshtml"
 using (Html.BeginForm("SetPassword", "Manage", FormMethod.Post))
{
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Manage\SetPassword.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Manage\SetPassword.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Manage\SetPassword.cshtml"
Write(Html.DevExpress().TextBoxFor(m => m.NewPassword, s => {
       s.Properties.Caption = "New Password";
       s.Properties.Password = true;
       s.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
       s.ShowModelErrors = true;
       s.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithText;
    }).GetHtml());

            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Manage\SetPassword.cshtml"
                
    
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Manage\SetPassword.cshtml"
Write(Html.DevExpress().TextBoxFor(m => m.ConfirmPassword, s => {
        s.Properties.Caption = "Confirm Password";
        s.Properties.Password = true;
        s.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
        s.ShowModelErrors = true;
        s.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithText;
    }).GetHtml());

            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Manage\SetPassword.cshtml"
                

            
            #line default
            #line hidden
WriteLiteral("    <br />\r\n");

            
            #line 30 "..\..\Views\Manage\SetPassword.cshtml"
    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Manage\SetPassword.cshtml"
Write(Html.DevExpress().Button(s => {
        s.Name = "SetPassword";
        s.Text = "Set password";
        s.UseSubmitBehavior = true;
    }).GetHtml());

            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Manage\SetPassword.cshtml"
                
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
